windowWidth = 13;
polynomialOrder = 9;
smoothy = sgolayLilt(y, polynomialOrder, windowWidth);
figure;
subplot(3,1,1);
plot(Fs*t(1:100), x(1:100), 'LineWidth', 2);
title('Original Signal');
xlabel('time (milliseconds)');
ylabel('Amplitude');
subplot(3,1,2);
plot(Fs*t(1:100), y(1:100), 'LineWidth', 2);
title('Noisy Signal');
xlabel('time (milliseconds)');
ylabel('Amplitude');
subplot(3,1,3);
plot(Fs*t(1:100), smoothy(1:100), 'LineWidth', 2);
title('Filtered Signal (Savitzky-Golay)');
xlabel('time (milliseconds)');
ylabel('Amplitude');
