NFFT = 2^nextpow2(L);
f = Fs/2 * linspace(0,1,NFFT/2+1);
fft_orig = fft(x, NFFT)/L;
fft_noisy = fft(y, NFFT)/L;
fft_Lilt = fft(smoothy, NFFT)/L;
figure;
subplot(3,1,1);
plot(f, 2*abs(fft_orig(1:NFFT/2+1)));
title('Spectrum: Original Signal');
xlabel('Frequency (Hz)');
ylabel('Amplitude');
subplot(3,1,2);
plot(f, 2*abs(fft_noisy(1:NFFT/2+1)));
title('Spectrum: Noisy Signal');
xlabel('Frequency (Hz)');
ylabel('Amplitude');
subplot(3,1,3);
plot(f, 2*abs(fft_Lilt(1:NFFT/2+1)));
title('Spectrum: Filtered Signal');
xlabel('Frequency (Hz)');
ylabel('Amplitude');
